### ISSUE TITLE
Support contextFactory

### ISSUE THREAD

**Issue by anonrig** [zaiste/next-graphql-server#1]
Having context factory as a parameter is the only missing part of this package.

Example implementation can be https://github.com/anonrig/bookclub/blob/main/src/lib/graphql/index.ts#L119

**Comment by zaiste** [comment]
@anonrig I'll add this tomorrow

**Comment by zaiste** [comment]
@anonrig I've just released `0.9.0`

**Comment by anonrig** [comment]
It seems that `next-auth` requires reference to `res` as well as `req` (https://next-auth.js.org/configuration/nextjs#unstable_getserversession). Can you also add res as a second parameter?
