### ISSUE TITLE
[Suggestion] Support for the Edge Runtime

### ISSUE THREAD

**Issue by alvarlagerlof** [zaiste/next-graphql-server#2]
https://vercel.com/docs/concepts/functions/edge-functions

**Comment by zaiste** [comment]
@alvarlagerlof Thanks for the suggestion. The support is already there. You need to pass `edge: true` to `createGraphQLHandler` and it will owrk

**Comment by alvarlagerlof** [comment]
> @alvarlagerlof Thanks for the suggestion. The support is already there. You need to pass `edge: true` to `createGraphQLHandler` and it will owrk

Yes! I figured it out and it seems to work great. Forgot to close the issue.

**Comment by alvarlagerlof** [comment]
I ended up going for graphql-yoga since that option seemed undocumented.
